import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Sheard/Header";
import Footer from "@/components/Sheard/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="mytheme">
      <body className={inter.className}>
        <Header></Header>
        <div className="container mx-auto">{children}</div>
        <Footer></Footer>
      </body>
    </html>
  );
}
